### ISSUE TITLE
Tabs behave weirdly

### ISSUE THREAD

**Issue by lilyyllyyllyly** [m0thman70/Atto-Editor#2]
When opening a file that has tab characters, the lines containing tabs are cutoff at the beginning. When hovering over them, The entire line shifts over to the left so that the tab is the size of a single space, and moving the cursor reveals the characters that were cutoff. See the attached video.

https://github.com/user-attachments/assets/c51da7bd-b90a-4929-8709-db274740a973

**Comment by m0th05** [comment]
its fixed in the recent patch 1, you should be fine now, it was simply a lack of tab handling and tab function
